### PR TITLE
Wishlist management

### PR DESCRIPTION
**Pull request by prajwalzingare**
- I have created the wishlist page design in this branch.
-  The wishlist functionality allows users to save their favorite products and view them later. 
-  The page displays product images, titles, ratings, prices, and a 'Move to Cart' button.
- Only UI in this branch for testing and understanding the logic
- [Deploy Preview](https://deploy-preview-4--organico-store.netlify.app/)

### CODE REVIEW

**Review by chhakuli123 — APPROVED** [review]
Your minimalist design aesthetic creates a clean and uncluttered interface, allowing the user's focus to be solely on the wishlist items themselves.

The choice of a neutral color scheme with subtle accents brings a sense of elegance and sophistication to the UI. The layout is straightforward and intuitive, making it effortless to browse and manage the wishlist.

**Comment by prajwalzingare** [comment]
> Your minimalist design aesthetic creates a clean and uncluttered interface, allowing the user's focus to be solely on the wishlist items themselves.
> 
> The choice of a neutral color scheme with subtle accents brings a sense of elegance and sophistication to the UI. The layout is straightforward and intuitive, making it effortless to browse and manage the wishlist.

thanks for detail review

**Comment by ichiragtaluja** [comment]
lgtm

**Review by ichiragtaluja — APPROVED** [review]
lgtm Awesome choice of colors.

**Comment by prajwalzingare** [comment]
> lgtm Awesome choice of colors.

thanks for review

**Pull request merged**
