### PR TITLE
User auth

### LINKED ISSUE #6: Signup Form Validation Error
- When submitting the signup form, the following validation errors occur:

First Name: The first name field should only contain letters.
Last Name: The last name field should only contain letters.
Email: Please enter a valid email address.
Password: The password should contain a minimum of 8 characters, including at least one uppercase letter, one lowercase letter, one digit, and one special character.
Confirm Password: The password confirmation does not match the entered password.
These validation errors prevent the form from being submitted and require the user to correct the highlighted fields before proceeding with the signup process.

### PR DESCRIPTION
**Pull request by prajwalzingare**
- This branch contains the implementation of user authentication functionality, including signup and login forms.
-  It handles user registration, login, and secure authentication using tokens. 
- The branch is dedicated to building and refining the user authentication feature of the application.
[Deploy Preview](https://deploy-preview-5--organico-store.netlify.app/)

### CODE REVIEW

**Review by chhakuli123 — CHANGES_REQUESTED** [review]
-  I reviewed the code and identified an issue with the sign-up functionality. It seems that users can successfully sign up without filling in any data, resulting in an empty user entry being created in the local storage. This behavior could lead to unexpected issues and data inconsistencies.
git


git 2

- I recommend implementing validation checks on the sign-up form to ensure that all required fields are filled before allowing the sign-up process to proceed. This will help maintain data integrity and improve the user experience by preventing empty user entries.

**Comment by prajwalzingare** [comment]
> * I reviewed the code and identified an issue with the sign-up functionality. It seems that users can successfully sign up without filling in any data, resulting in an empty user entry being created in the local storage. This behavior could lead to unexpected issues and data inconsistencies.
>   git
> 
> git 2
> 
> * I recommend implementing validation checks on the sign-up form to ensure that all required fields are filled before allowing the sign-up process to proceed. This will help maintain data integrity and improve the user experience by preventing empty user entries.

ok thanks for reviewing i am creating issue for that and will work on this

**Comment by prajwalzingare** [comment]
@chhakuli123   issue is fixed #6

**Comment by chhakuli123** [comment]
> @chhakuli123 issue is fixed #6

Well done, all working fine.Ready to close issue.

**Review by chhakuli123 — APPROVED** [review]

**Comment by pranita09** [comment]
All good. Everything is working fine.

**Review by pranita09 — APPROVED** [review]
Great work on the User Authentication branch. Code looks clean and well-implemented. Well done! Ready to merge.

**Comment by prajwalzingare** [comment]
> Great work on the User Authentication branch. Code looks clean and well-implemented. Well done! Ready to merge.

thanks, pranita for the code review

**Pull request merged**
